// CRUD
export const GET_CATEGORIES = 'GET_CATEGORIES'

export const BUY_BOOK = 'BUY_BOOK'

export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'

// SORTER
export const SORT_BY = 'SORT_BY'
export const NAME_ASC = 'NAME_ASC'
export const NAME_DESC = 'NAME_DESC'
export const PRICE_ASC = 'PRICE_ASC'
export const PRICE_DESC = 'PRICE_DESC'

// ORDER

export const GET_DETALLE_ORDER = 'GET_DETALLE_ORDER'

//ADMIN 

export const GET_USUARIOS = 'GET_USUARIOS'
export const GET_ORDERS = 'GET_ORDERS'

// QUESTIONS AND ANSWERS FROM DETAILS OF EACH BOOK 

export const POST_QUESTION = 'POST_QUESTION'
export const POST_ANSWER = 'POST_ANSWER'
export const GET_QA = 'GET_QA'
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS'
export const GET_ALL_ANSWERS = 'GET_ALL_ANSWERS'
