export const GET_CATEGORIES = 'GET_CATEGORIES'
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'

export const SORT_BY_NAME = 'SORT_BY_NAME'
export const SORT_BY_PRICE = 'SORT_BY_PRICE'

export const ASCENDENT = 'ASCENDENT'
export const DESCENDENT = 'DESCENDENT'
export const RESET_SORTS = 'RESET_SORTS'
